# SPDX-License-Identifier: Apache-2.0

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_ASSERT=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_BUILD_OUTPUT_META=y

CONFIG_ASSURELOOP_LOOP_PERIOD_MS=100
CONFIG_ASSURELOOP_LOOP_ITERATIONS=20
CONFIG_ASSURELOOP_ENABLE_STARTUP_BANNER=y
