# SPDX-License-Identifier: Apache-2.0
# Simulator-first MCUboot/image-signing path.
# This is used only when building with `west build --sysbuild`.

SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y
