# SPDX-License-Identifier: Apache-2.0
# Planned secure-boot path. This is not enabled by the default CI build yet.
# Use only on boards with a verified partition map and MCUboot support.

SB_CONFIG_BOOTLOADER_MCUBOOT=y
